//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeristandPythonInterop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeristandPythonInterop.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enusre that the arrays have the same length..
        /// </summary>
        internal static string ErrorMessageArraySizeDoesNotEqual {
            get {
                return ResourceManager.GetString("ErrorMessageArraySizeDoesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write channel in requested timeframe.
        /// </summary>
        internal static string ErrorMessageChannelSynchWrite {
            get {
                return ResourceManager.GetString("ErrorMessageChannelSynchWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different active project than requested..
        /// </summary>
        internal static string ErrorMessageDifferentProject {
            get {
                return ResourceManager.GetString("ErrorMessageDifferentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that a project is open before attempting this operation..
        /// </summary>
        internal static string ErrorMessageProjectIsNotOpen {
            get {
                return ResourceManager.GetString("ErrorMessageProjectIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine VeriStand path from Windows Registry..
        /// </summary>
        internal static string ErrorMessageRegistryKeyMissing {
            get {
                return ResourceManager.GetString("ErrorMessageRegistryKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that a project is open before attempting this operation..
        /// </summary>
        internal static string ErrorMessageShowHide {
            get {
                return ResourceManager.GetString("ErrorMessageShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veristand failed to terminate in the given Timeout..
        /// </summary>
        internal static string ErrorMessageVeriStandClose {
            get {
                return ResourceManager.GetString("ErrorMessageVeriStandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that VeriStand is launched before attempting this operation..
        /// </summary>
        internal static string ErrorMessageVeriStandIsNotLaunched {
            get {
                return ResourceManager.GetString("ErrorMessageVeriStandIsNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Launch VeriStand in the given timeout..
        /// </summary>
        internal static string ErrorMessageVeriStandLaunch {
            get {
                return ResourceManager.GetString("ErrorMessageVeriStandLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to undeploy project..
        /// </summary>
        internal static string ErrorMessageVeriStandUndeploy {
            get {
                return ResourceManager.GetString("ErrorMessageVeriStandUndeploy", resourceCulture);
            }
        }
    }
}
